import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className=" max-w-screen-xl mx-auto bg-black
       text-slate-50">
        <div className="px-4  py-4">
        <Navbar />
        <h1 className="text-8xl mt-8 mb-4 font-bold">Vinicius Sodré</h1>
        {children}
        </div>
        
        </body>
    </html>
  )
}
